### ISSUE TITLE
RTL seems to be MIT licensed but repo reports GPLv2

### ISSUE THREAD

**Issue by juliusbaxter** [CospanDesign/nysa-sdio-device#1]
The RTL has explicit MIT licence headers but the repo has a copy of the GPLv2 text in its LICENSE file.

I presume it was the intention to licence the IP under a permissive licence and the LICENSE file is an artifact of the repo being set up from the driver repo?

**Comment by cospan** [comment]
Wow, didn't even notice that. You're right I've changed the license file to MIT. Thanks for letting me know.
